"""unique

Revision ID: 157e8450381c
Revises: dbbc7a6c69c8
Create Date: 2023-07-21 18:38:56.816213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157e8450381c'
down_revision = 'dbbc7a6c69c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
