"""backref

Revision ID: 20190f5dd9a0
Revises: 68c3d95bf1d9
Create Date: 2023-07-22 00:10:23.717657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20190f5dd9a0'
down_revision = '68c3d95bf1d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
