"""CASCADE

Revision ID: 9fdf4763f6df
Revises: d865076e6887
Create Date: 2023-07-24 13:57:39.381560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdf4763f6df'
down_revision = 'd865076e6887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('journal_user_id_fkey', 'journal', type_='foreignkey')
    op.create_foreign_key(None, 'journal', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.create_foreign_key('journal_user_id_fkey', 'journal', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
