"""CASCADE for notes

Revision ID: a67c7679a519
Revises: 9fdf4763f6df
Create Date: 2023-07-24 14:00:39.195871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67c7679a519'
down_revision = '9fdf4763f6df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('user_id', 'note', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
