"""userid

Revision ID: d865076e6887
Revises: 20190f5dd9a0
Create Date: 2023-07-22 00:23:59.467640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd865076e6887'
down_revision = '20190f5dd9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key('user_id', 'note', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id', 'note', type_='foreignkey')
    op.drop_column('note', 'user_id')
    # ### end Alembic commands ###
